/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ForexChart: typeof import('./src/components/ForexChart.vue')['default']
    ReportPanel: typeof import('./src/components/ReportPanel.vue')['default']
    SidebarPanel: typeof import('./src/components/SidebarPanel.vue')['default']
    StatsRow: typeof import('./src/components/StatsRow.vue')['default']
    TimingsBar: typeof import('./src/components/TimingsBar.vue')['default']
  }
}
